[tool.poetry]
name = "ri-cloud-api"
version = "0.1.0"
description = "Local-hosted backend service bridging Sumo data into ResInsight over a FastAPI HTTP API."
authors = ["Jørgen Herje <jorgen.herje@gmail.com>"]
readme = "README.md"
packages = [{ include = "ri_cloud_api" },
            { include = "ri_cloud_services", from = "ri_cloud_api/libs/services/src" },
            { include = "ri_cloud_core_utils", from = "ri_cloud_api/libs/core_utils/src" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
uvicorn = { extras = ["standard"], version = "^0.32.0" }
pydantic = "^2.9.0"
fmu-sumo = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
