name: ri-cloud-api

permissions:
  contents: read

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit locally
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - name: Install poetry and dependencies
        run: |
          set -x
          pip install --upgrade pip
          pip install poetry==2.4.1
          poetry config virtualenvs.create false

          # Check that the lock file is consistent with pyproject.toml
          poetry check --lock

          poetry install

      - name: Lint with ruff
        run: ruff check .

      - name: Check formatting with ruff
        run: ruff format --check --diff .

      - name: Type check with mypy
        run: mypy ri_cloud_api
